name: test

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies 
      run: yarn install
    - name: Run linting tests
      run: yarn run test-lint

  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies 
      run: yarn install
    - name: Run type tests
      run: yarn run test-types
