name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '12.13.0'
    - name: Install Dependencies 
      run: yarn install
    - name: Linting
      run: yarn run test-lint
    - name: Types
      run: yarn run test-types
